kind: pipeline
name: Build & Pack

steps:
  - name: build
    image: cortezaproject/corteza-webapp-builder
    volumes:
      - name: webapp-build
        path: /var/build
    commands:
      - sh build.sh

  - name: build image
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
      tags: [ "${APP_VERSION/master/latest}" ]
      username: { from_secret: docker_hub_username }
      password: { from_secret: docker_hub_password }

volumes:
  - name: webapp-build
    host:
      path: /var/build/drone/webapp-build
