kind: pipeline
name: Build & Pack

steps:
  - name: collect
    image: cortezaproject/corteza-webapp-builder
    volumes:
      - name: webapp-build
        path: /var/build
    commands:
      - sh collect.sh
      - sh build.sh
    when:
      ref:
        - refs/heads/master
        - refs/heads/beta
        - refs/heads/feature-*
        - refs/tags/20??.*.*
      events: [ tag, push ]

  - name: build image
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
      tags:
        - "${APP_VERSION/master/latest}"
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password


trigger:

volumes:
  - name: webapp-build
    host:
      path: /var/build/drone/webapp-build
